import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/navbar";
import Providers from "./Providers";
import Script from "next/script";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lumora Bhutan",
  description: "Generated by Lumora Bhutan",
  icons: {
    icon: "/lumora_logo.png",
    shortcut: "/lumora_logo.png",
    apple: "/lumora_logo.png",
  },
};

/* ✅ Inline Client Component */
function ConditionalNavbar() {
  "use client";
  const pathname = usePathname();

  if (pathname.startsWith("/dashboard")) return null;

  return <Navbar />;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          id="organization-logo"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              url: "https://lumorabhutan.com",
              logo: "https://lumorabhutan.com/logo.png",
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased relative`}
      >
        <Providers>
          <ConditionalNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
