// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import NavbarClient from "../component";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for SEO and Social Sharing
export const metadata: Metadata = {
  title: "Lumora Bhutan",
  description: "Generated by Lumora Bhutan",
  icons: {
    icon: [
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
  openGraph: {
    title: "Lumora Bhutan",
    description: "Generated by Lumora Bhutan",
    url: "https://lumorabhutan.com",
    siteName: "Lumora Bhutan",
    images: [
      {
        url: "https://lumorabhutan.com/logo.png",
        width: 1200,
        height: 630,
        alt: "Lumora Bhutan Logo",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

// Organization JSON-LD for Google Rich Results
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Lumora Bhutan",
  url: "https://lumorabhutan.com",
  logo: "https://lumorabhutan.com/logo.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* JSON-LD structured data for Google */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased relative`}
      >
        <Providers>
          <NavbarClient />
          {children}
        </Providers>
      </body>
    </html>
  );
}
